set -T to linux if $TERM is dumb
artix-linux/runit-rc pull request #3
Opened 2019-09-11 20:20 UTC by Dudemanguy911

Sorry for sending this one to a mirror but gitea registration is closed.

It's possible for `$TERM` to be `dumb` on bootup which causes `tput colors` to fail and thus the rest of the script. Workaround this by simply assuming $TERM can be linux if it is `dumb`.

2019-09-12 12:39 UTC, thefallenrat commented
Hmm, Has this been tested on users with `$TERM` set to empty? Also, I'm interested if we could follow the **openRC** way to set colors in terminal

https://github.com/OpenRC/openrc/blob/5427783fdf3d183ea4e63afc507c31d88f0d2c9c/etc/rc.in#L14

2019-09-12 12:58 UTC, Dudemanguy commented
I don't think `$TERM` should be set manually here since I believe whatever init system you're using should do that at some point. At least when I've been testing this with s6, the `$TERM` variable gets set sometime after the runit-rc scripts get run hence why I need this patch. That being said, it definitely makes sense to include an empty `$TERM` in the check as well. `tput colors` expects a value for `$TERM` so an empty `$TERM` will also fail.

I guess the weakness here is that it assumes if your `$TERM` is empty or dumb, it will at some point get set to something "proper" later (i.e. `linux` or something else that has color support).

2019-09-12 23:59 UTC, thefallenrat approved these changes

2019-09-13 01:28 UTC, konimex requested changes

2019-09-13 01:28 UTC, konimex commented on script/functions.in
> +if [[ -z "$TERM" -o "$TERM" = "dumb" ]]; then
Use `||` instead of `-o`.

2019-09-13 01:30 UTC, thefallenrat commented on script/functions.in
> +if [[ -z "$TERM" -o "$TERM" = "dumb" ]]; then
Don't think you need || for that

2019-09-13 01:31 UTC, konimex commented on script/functions.in
> +if [[ -z "$TERM" -o "$TERM" = "dumb" ]]; then
Rationale: https://github.com/koalaman/shellcheck/wiki/SC2110

On that note, I should probably rewrote the rc to be shellcheck compliant.

2019-09-13 01:32 UTC, Dudemanguy commented on script/functions.in
> +if [[ -z "$TERM" -o "$TERM" = "dumb" ]]; then
Makes sense to me.

2019-09-13 01:33 UTC, konimex approved these changes

2019-09-13 01:55 UTC, thefallenrat commented on script/functions.in
> +if [[ -z "$TERM" -o "$TERM" = "dumb" ]]; then
Then don't use `[[]]`, use `[]` instead

2019-09-13 01:59 UTC, konimex commented on script/functions.in
> +if [[ -z "$TERM" -o "$TERM" = "dumb" ]]; then
If it's POSIX sh, then I'd be fine with `[`. But bash has `[[`, why don't we use it to our advantage?

2019-09-13 02:02 UTC, konimex commented on script/functions.in
> +if [[ -z "$TERM" -o "$TERM" = "dumb" ]]; then
Also, see https://github.com/koalaman/shellcheck/wiki/SC2166

2019-09-13 04:52 UTC, konimex commented
Merged manually. See https://github.com/artix-linux/runit-rc/commit/451fe75e69527cf656451517def18f0e07193675

2019-09-13 04:52 UTC, closed without merging